### ISSUE TITLE
AttributeError: 'int' object has no attribute 'bit_count'

### ISSUE THREAD

**Issue by ufukbolat1** [testflows/TestFlows-Combinatorics#1]
Hello,

I already installed the library (testflows.combinatorics ).

But when I try to run the first example, I see the following error:

```
from testflows.combinatorics import Covering

parameters = {"a": [0, 1], "b": ["a", "b"], "c": [0, 1, 2], "d": ["d0", "d1"]}

print(Covering(parameters, strength=2))
```

error:

```
`AppData/.../pip_testflows.py
Traceback (most recent call last):
  File "c:/Users/.../pip_testflows.py", line 5, in <module>
    print(Covering(parameters, strength=2))
  
File "C:\...\Python38\site-packages\testflows\combinatorics\covering_array.py", line 61, in __init__        
    self.array = self.generate()
  
File "C:\...\Python38\site-packages\testflows\combinatorics\covering_array.py", line 356, in generate       
    π = self.horizontal_extension(t, i, π)
  
File "C:\...\Python38\site-packages\testflows\combinatorics\covering_array.py", line 206, in horizontal_extension
    coverage, bitmap = self.calculate_coverage(t, i, new_test, π)
 
File "C:\...\Python38\site-packages\testflows\combinatorics\covering_array.py", line 324, in calculate_coverage
    current_coverage = (bitmap).bit_count()

**AttributeError: 'int' object has no attribute 'bit_count'`**

```
Could you support me?

**Comment by vzakaznikov** [comment]
Hi @ufukbolat1, I apologize for not replying sooner. This module was moved to testflows.core (https://github.com/testflows/TestFlows-Core/tree/master/testflows/combinatorics).

Yes, you are right. I need to update the code.

**Comment by vzakaznikov** [comment]
Actually, the code has been updated. Please upgrade to the latest version `1.1.230921.1194623`.

```bash
pip3 install testflows.combinatorics==1.1.230921.1194623
```

```
$ cat test.py 
from testflows.combinatorics import Covering

parameters = {"a": [0, 1], "b": ["a", "b"], "c": [0, 1, 2], "d": ["d0", "d1"]}

print(Covering(parameters, strength=2))
```

```
$ python3 test.py 
CoveringArray({'a': [0, 1], 'b': ['a', 'b'], 'c': [0, 1, 2], 'd': ['d0', 'd1']},2)[
6
a b c d
-------
0 a 2 d0
0 b 1 d1
1 a 1 d0
1 b 2 d1
0 a 0 d1
1 b 0 d0
]
```
